name: Build APK Android
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        # تسطيب كل برامج لينكس الأساسية اللي الأندرويد بيحتاجها
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev

      - name: Install Buildozer & Cython
        # السر كله هنا: إجبار السيرفر على استخدام Cython أقل من 3.0 عشان Pygame متضربش
        run: |
          pip install --upgrade pip
          pip install buildozer virtualenv
          pip install "Cython<3.0"

      - name: Build the APK
        # إعطاء موافقة أوتوماتيكية (yes) على شروط الأندرويد عشان السيرفر ميقفش مستني رد
        run: |
          yes | buildozer android debug

      - name: Upload the APK
        uses: actions/upload-artifact@v4
        with:
          name: Bubble-Shooter-Omar-APK
          path: bin/*.apk
